### PR TITLE
Issue66

### PR DESCRIPTION
**Pull request by jainaman224**
Fixed some typos.

### CODE REVIEW

**Comment by jainaman224** [comment]
How to send iterable list instead of nested array to utils.py...?
Please help. It is working well when I embed unique function in instruction_colors function itself but it is disturbing the test.

**Comment by niccokunzmann** [comment]
Can you publish the changes to the requirements file in an extra pull-request?
This way, I can merge them already. As a rule for fast merging: create small pull-requests with minimal changes - then, I do not have to wait for the more complex changes to work.

**Comment by niccokunzmann** [comment]
There are two kinds of tests failing:

1. This test testing that the order of instruction_colors is the same as they appear in the file: https://travis-ci.org/fossasia/knittingpattern/jobs/205440185#L759
2. This test testing that the function unique is used and mocking it: https://travis-ci.org/fossasia/knittingpattern/jobs/205440185#L735

**Comment by jainaman224** [comment]
@niccokunzmann I think imap is deprecated and we have to use groupby with mao which would be slow. Still I will let you know by implementing both. Set implementation is 10 times faster than current implementation on repl.it .

**Comment by jainaman224** [comment]
Can we work on sets...?
Then we only need to do union which will increase efficiency.

**Pull request merged**
